### ISSUE TITLE
Use with input mask

### ISSUE THREAD

**Issue by ianitsky** [NewOldMax/react-form-validator-core#11]
Hi

I'm trying to use this lib with react-input-mask like the example:

[material-ui + text-mask demo](https://codesandbox.io/s/yl8p9jvq9)

But if I bu like the example, nothing happens.

Have any idea to make this work?

**Comment by NewOldMax** [comment]
Hi,
your issue isn't related to this library. I guess you're talking about [react-material-ui-form-validator](https://github.com/NewOldMax/react-material-ui-form-validator). Please, open it there and provide more info, like your code example
