### ISSUE TITLE
Validity of the whole form

### ISSUE THREAD

**Issue by pavanshinde47** [NewOldMax/react-form-validator-core#13]
Hi,

Can you add a property or method to the ValidatorForm to see if the whole form is valid or not.

Something like 

`isValid=()=>
{
  this.childs.map(child => {
  if(child.isValid)
  {
    return true
  }
  });
  return false
}`

**Comment by NewOldMax** [comment]
Hi,
for now you can do something like this
````javascript
<ValidatorForm ref={r => (this.form = r)} >


runFormvalidation = () => {
    const result = this.form.walk(this.form.childs); // result will be true or false
}
````

**Comment by vineet-agrawal96** [comment]
Hi

 I called runFormvalidation  function from render method then showing continuously warning.

`
runFormvalidation = () => {
    if(!isEmpty(this.refs)){
    const result = this.refs.form.walk(this.refs.form.childs); // result will be true or false
    return result
  }
}
`

warning.js:33 Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor)

**Comment by NewOldMax** [comment]
As you can see in your warning message, you shouldn't call this function in render method. You should do it in some event action, like `onChange`
````javascript
<ValidatorForm onChange={this.runFormvalidation} />
````

**Comment by NewOldMax** [comment]
From version `0.4.3` you can use `isFormValid` method

**Comment by pavanshinde47** [comment]
@NewOldMax Thanks

**Comment by arosas-atix** [comment]
@NewOldMax Hi, I'm currently using the library at the latest version (0.4.4), and I couldn't find a way to use that method, since it's not exposed in the react class. Could you please post an example of how to use it?
I tried using it the same way as ```addValidationRule```

**Comment by NewOldMax** [comment]
@arosas-atix 
````javascript
<ValidatorForm
    ref={r => (this.form = r)}
>

...

this.form.isFormValid();
````
