### ISSUE TITLE
Package is not published pre-compiled

### ISSUE THREAD

**Issue by AbiriAmir** [NewOldMax/react-form-validator-core#14]
This package is not published pre-compiled. So create-react-app can not build this package with this error:

> Failed to minify the code from this file

Please refer to this link:
[https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)

Thank you

**Comment by NewOldMax** [comment]
You have this issue because of webpack which uses `uglify-js` to build, but this package has `react-lifecycles-compat@3.0.0` dependency and it has some unminified es6 code so `uglify-js` throws error. As I see they already fixed that, so I will update this dep this week and build should be ok

**Comment by ulisesbocchio** [comment]
I'd appreciate the fix too... at least a `^` on the dependency

**Comment by NewOldMax** [comment]
Should be fixed in [0.4.4](https://github.com/NewOldMax/react-form-validator-core/releases/tag/0.4.4)
