### ISSUE TITLE
ValidatorForm should probably have the `noValidate` prop by default

### ISSUE THREAD

**Issue by bboure** [NewOldMax/react-form-validator-core#15]
Hi, I am playing a bit with the validators and so far it looks great.
I just came across this little issue:

![image](https://user-images.githubusercontent.com/7089997/38892969-211ecdd8-4289-11e8-861c-5a951b71f384.png)

I used a `<TextValidator>` component (from [react-material-ui-form-validator](https://github.com/NewOldMax/react-material-ui-form-validator)) with `type="email"` and I got the browser's validator kicking.

Solution was to add `noValidate` to `<ValidatorForm>` but since this library is all about doing custom validation, I guess it should probably come by default [here](https://github.com/NewOldMax/react-form-validator-core/blob/master/src/ValidatorForm.jsx#L134)?

What do you think?

**Comment by NewOldMax** [comment]
It's not bad to have ability to use native validation if someone wants it. Otherwise it will take some coding to enable it, if we put `noValidate` as default
