### ISSUE TITLE
Async Validator Rule

### ISSUE THREAD

**Issue by Donskelle** [NewOldMax/react-form-validator-core#17]
Hey Guys, i want to add a new validation rule to check if mail is available.
Somethink like 
```
ValidatorForm.addValidationRule('isEmailAvailable', (value) => {
        axios.post('/api/users/emailavailable', formDataClear)
            .then((response) => {
                if (response.data == "ok") {
                    return true
                } 
                return false
        })
    });
```
Is there a way to set async validators?

**Comment by NewOldMax** [comment]
Hi,
currently you can't achieve it in some clear and reusable way
but you can try to do something like [this](https://codesandbox.io/s/rjjk7jznyo)

**Comment by Donskelle** [comment]
Nice i can use that. Thanks for quick response.
