### ISSUE TITLE
Update dependency of react-lifecycles-compat to 3.0.2+

### ISSUE THREAD

**Issue by joaom182** [NewOldMax/react-form-validator-core#18]
Hello,

I've using `react-form-validator-core@0.4.3` on my project scaffolded by `create-react-app` and on build to production step `react-scripts build` throws the error:

```
Failed to minify the code from this file:
        ./node_modules/react-lifecycles-compat/react-lifecycles-compat.es.js:64
```
The real problem is related [here](https://github.com/reactjs/react-lifecycles-compat/issues/25), and the solution is the `react-form-validator-core` upgrade the dependency version of `react-lifecycles-compat` to `3.0.2+` if you are using version `0.4.3`.

On version `0.4.4` all works as expected.

**Comment by NewOldMax** [comment]
So it's not a problem, right? just use `0.4.4`

**Comment by joaom182** [comment]
Yes, it's not a problem, is just a warning to prevent other users from experiencing this.
