### ISSUE TITLE
Maximum call stack size exceeded with custom validator

### ISSUE THREAD

**Issue by Debananda** [NewOldMax/react-form-validator-core#31]
Upon adding custom validations, on no error the validator is getting called infinite times. I think this is the same issue https://github.com/christianalfoni/formsy-react/issues/298. 

"react": "^16.4.2",
"react-form-validator-core": "^0.4.4",

**Comment by NewOldMax** [comment]
Hi
can you reproduce your issue [here](https://codesandbox.io/s/p52x38v22m)?

**Comment by Debananda** [comment]
My mistake.. sometime I can't think properly. The infinite call was due improper coding :)
Thanks a lot
