### ISSUE TITLE
Validate onBlur

### ISSUE THREAD

**Issue by eklemen** [NewOldMax/react-form-validator-core#40]
Have any plans for allowing validate `onBlur` as a prop/config as well? I can look into opening a PR if I get some free time. Thanks for the package, it was exactly what I was looking for.

**Comment by NewOldMax** [comment]
Hi, here is an [onBlur example](https://github.com/NewOldMax/react-material-ui-form-validator/wiki/How-to-onBlur)

**Comment by eklemen** [comment]
Thanks @NewOldMax , i am using Semantic UI React and their `Form.Input` i guess is a functional component so I get an error I cannot use `ref`'s on functional components. I might be able to wrap it or extract it somehow, but good to know theres an onBlur example.
