### ISSUE TITLE
dropdown and desc input type validation is not here.

### ISSUE THREAD

**Issue by DeepakM02** [NewOldMax/react-form-validator-core#49]
There are validators for text. I want to use these validator for select, desc and other input type along with text type. I am not getting what should I do.

**Comment by NewOldMax** [comment]
Validator checks the `value` of component props. You should just pass it. What problem do you have?

**Comment by DeepakM02** [comment]
I am not able to get whole form validity and use form validator in select, desc input type. when I use in desc then it converts to input type text. How to add validation rules with multiple parameter.

**Comment by NewOldMax** [comment]
can you reproduce your issue [here](https://codesandbox.io/s/new)?

**Comment by DeepakM02** [comment]
Yeah, Finally I have added  [link](https://codesandbox.io/s/4q0ynm2or4?fontsize=14)  I applied validator for input type text but for type **select, desc**, and others it is not working and I am not able to use form methods means how to disable button if a form is invalid.

**Comment by NewOldMax** [comment]
You're using this library wrong. You should create your own SelectValidator component in the same way as TextValidator in readme. Also there is no `<input type="select">`, but `<select>`

**Comment by DeepakM02** [comment]
yeah I did as you said above but it did not work i will share the code and I am not able to use forms method to disable submit button when form invalid.

**Comment by NewOldMax** [comment]
you should use `options={this.options()}`

**Comment by NewOldMax** [comment]
https://codesandbox.io/s/v6n31l8700
