### ISSUE TITLE
It's not possible to make validation fields dependent on each other

### ISSUE THREAD

**Issue by BFUculsion** [NewOldMax/react-form-validator-core#50]
For example, if you have a New Password and a Confirm New Password field, you can't make the Confirm New Password field validation switch to true if the New Password field changes.

**Comment by BFUculsion** [comment]
Also, we're a user of your library and would like to offer our product to you for free. We enable your users to give you direct feature feedback, and want to give back to those projects we use.
https://www.uclusion.com/

**Comment by NewOldMax** [comment]
Hi
if you want to validate some other field while current field changes, you should do it manually (call `validate` function for specific field or even for all form)

**Comment by BFUculsion** [comment]
Hi, How does that work? I couldn't find that in the docs.

Thanks, Ben

**Comment by BFUculsion** [comment]
Er, to be more specific, I couldn't figure out how to get the object and
call validate on it. Do you have an example?

Thanks, Ben

**Comment by NewOldMax** [comment]
@BFUculsion sorry, I didn't see your answer. Can you reproduce your issue here https://codesandbox.io/s/new ?

**Comment by DeepakM02** [comment]
@NewOldMax please check this [https://codesandbox.io/s/distracted-smoke-0gvf9](link) . I want both input field dependent to each other.
