### ISSUE TITLE
Why there is no ValidatorForm.removeValidationRule?

### ISSUE THREAD

**Issue by mgustus** [NewOldMax/react-form-validator-core#51]
Hi,

After adding a custom validation rule with `ValidatorForm.addValidationRule` in `componentDidMount()`, I think it is reasonable to remove it in `componentWillUnmount()`. It looks like there could be a memory leak because the custom rule function stays in the Rules collection with all its closures.
Why there is no `ValidatorForm.removeValidationRule`?

Thanks.

**Comment by NewOldMax** [comment]
There is no memory leak there. Only if you add new rules every time with unique names. But `removeValidationRule` function makes sense, I will add it later

**Comment by mgustus** [comment]
The problem is that `Rules` is a static collection that is never destroyed. So if I add a rule that uses `state` or `props` of some component, this component will remain in memory forever.

**Comment by NewOldMax** [comment]
@mgustus check the 0.6.4 version

**Comment by mgustus** [comment]
great!
Thank you 👍
