### ISSUE TITLE
@NewOldMax please check this [https://codesandbox.io/s/distracted-smoke-0gvf9](link) . I want both input field dependent to each other.

### ISSUE THREAD

**Issue by DeepakM02** [NewOldMax/react-form-validator-core#54]
@NewOldMax please check this [link]( https://codesandbox.io/s/distracted-smoke-0gvf9 ) . I want both input field dependent to each other.

_Originally posted by @DeepakM02 in https://github.com/NewOldMax/react-form-validator-core/issues/50#issuecomment-505376196_

**Comment by NewOldMax** [comment]
Hi,
you can just run form whole form validation like [here](https://codesandbox.io/s/so6cp)
If you don't need whole form validation, you can set ref for needed input and call `validate` manually
```jsx

  handleFirstInputChange(e) {
    const { name, value } = e.target;
    this.setState(
      {
        [name]: value
      },
      () => this.secondInputRef.validate(this.secondInputRef.state.value)
    );
  }
```

**Comment by DeepakM02** [comment]
Hey @NewOldMax, Can I use validatorListener for both min and max input field in this [example](https://codesandbox.io/s/brave-kare-zlerz) and pass props minNumber and maxNumber into validators?

**Comment by NewOldMax** [comment]
You can try, why not
