### ISSUE TITLE
Setting props dynamically doesn't work

### ISSUE THREAD

**Issue by flaviusmatis** [NewOldMax/react-form-validator-core#60]
I'm trying to set the "instantValidate" property dynamically and there is no effect.

I've also tried to use refs like you suggested here (https://github.com/NewOldMax/react-form-validator-core/issues/33#issuecomment-507669085), and I can successfully alter the property via the ref, but it as no real effect.

**Comment by NewOldMax** [comment]
Hi. Can you reproduce your issue on https://codesandbox.io/s/new?

**Comment by flaviusmatis** [comment]
There you go: https://codesandbox.io/s/sleepy-browser-35d30

instantValidate is initially false; after clicking the submit button it becomes true, but instant validation still doesn't work

**Comment by NewOldMax** [comment]
try to do something like this
```jsx
  enableInstantValidate = e => {
    this.form.instantValidate = true;
    this.form.childs.forEach(element => {
      element.instantValidate = true;
    });
  };
```

**Comment by flaviusmatis** [comment]
Your last suggestion works.

Do you also plan to add support to be dynamically changed or should I stick with this solution?

**Comment by NewOldMax** [comment]
It's really specific case and I believe it can be done without dynamic changes. So no plans to support it.
