### ISSUE TITLE
cannot locate @types/react-form-validator-core

### ISSUE THREAD

**Issue by hutan624** [NewOldMax/react-form-validator-core#62]
I cannot find the @types/eact-form-validator-core and I cannot use  react-form-validator-core yet in a  typescript project. Linting is failing on every component extending ValidatorComponent.
Any suggestion?

**Comment by NewOldMax** [comment]
Hi,
1. You can exclude this part from typescript linting
2. You can write your own @types and use them

I don't use typescript so I cannot support it in this library.
Community maintains https://www.npmjs.com/package/@types/react-material-ui-form-validator
for my other package, so you can do it as well, or offer them to add @types/react-form-validator-core
