### ISSUE TITLE
Is there any way to have ValidateOnChangeAfterInitialBlur ?

### ISSUE THREAD

**Issue by sureshsevarthi** [NewOldMax/react-form-validator-core#64]
**ValidateOnChangeAfterInitialBlur**
* when user focuses field, there is no error and the field is empty, no validation nor  error message is displayed till the blur event.
* If the user focuses the field, there is no error and the field has values, on change(instantValidation) the validation is performed
* If the user focuses the field with an error, the validation is performed on change(instantValidation).

**Comment by NewOldMax** [comment]
Please create an example on https://codesandbox.io/s/ so it will be better to analyze

**Comment by sureshsevarthi** [comment]
I'm asking for new feature that can have **"ValidateOnChangeAfterInitialBlur"**.
As of now we only have 
* InstantValidate --- onChange
* debounceTime --- setTime

Is there any chance we can have **ValidateOnChangeAfterInitialBlur**
That would be appreciated.

**Comment by NewOldMax** [comment]
It's really corner case so no plans to add it. You must implement it by yourself

You can get some ideas about blur validation [here](https://github.com/NewOldMax/react-material-ui-form-validator/wiki/How-to-onBlur)

**Comment by sureshsevarthi** [comment]
Thanks @NewOldMax, this is helpful, much appreciated. you really made a great package for form validation. thanks again.

> It's really corner case so no plans to add it. You must implement it by yourself
> 
> You can get some ideas about blur validation [here](https://github.com/NewOldMax/react-material-ui-form-validator/wiki/How-to-onBlur)
