### ISSUE TITLE
Warning: Legacy context API has been detected within a strict-mode tree.

### ISSUE THREAD

**Issue by kadamgreene** [NewOldMax/react-form-validator-core#76]
First let me say that your components are great.  But I'm using them in an application that is built using functions (+ hooks) rather than classes.  and I get this "error":

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.
Please update the following components: TextValidator, ValidatorForm
Learn more about this warning here: https://fb.me/react-legacy-context

**Comment by NewOldMax** [comment]
fixed in `1.0.0`
