### ISSUE TITLE
Need Textarea validation

### ISSUE THREAD

**Issue by dineshoctal** [NewOldMax/react-form-validator-core#84]
I need to add the textarea and validation, how can I achieve this.

`<textarea
                    className="form-control"
                    name="description"
                    placeholder="Write here.."
                    onChange={(e) => {
                      setMessage(e.target.value);
                    }}
                    validators={["required", "maxStringLength: 200"]}
                    errorMessages={[
                      "Please enter credit description",
                      "Please enter less than 200 characters",
                    ]}
                  ></textarea>`

please advise me.

Thanks,

**Comment by NewOldMax** [comment]
@DineshOctal Hi,
you can follow [wiki](https://github.com/NewOldMax/react-form-validator-core/wiki/Universal-validation-feedback-example) example
