### ISSUE TITLE
Error: resetValidations is not a function.

### ISSUE THREAD

**Issue by zhr1130** [NewOldMax/react-form-validator-core#9]
I tried to use resetValidations, however I got error: this.form.resetValidations is not a function. And when I looked into the source in browser, I didn't even see the function under ValidatorForm.js. 
I think the reason is we didn't bind it correctly in ValidatorForm.

**Comment by zhr1130** [comment]
#10 

I opened a PR to fix it. Would someone take a look ?

**Comment by NewOldMax** [comment]
Hi,
Can you show your code? Because it's working fine for me. And you can see on [demo](https://newoldmax.github.io/react-material-ui-form-validator/) site (Reset form example) that it's working too

**Comment by NewOldMax** [comment]
@zhr1130  Make sure that you're using 0.4.1 version

**Comment by NewOldMax** [comment]
Not acceptable since 0.4.3
