### ISSUE TITLE
Polyfill library throwing react-17 dependency warning

### ISSUE THREAD

**Issue by TJHeeringa** [NewOldMax/react-form-validator-core#96]
![afbeelding](https://user-images.githubusercontent.com/16029718/202260888-8ea1e0e6-6b5e-49a6-830d-b663fb6e0f60.png)

`create-react-context` throws a dependency warning. Create react context is a polyfill library, so you could consider removing it.

**Comment by rstar2** [comment]
**create-react-context** should be removed if this **react-form-validator-core**  is for React 17/18 , especially for the v3. It could be left for the older versions that support React16

**Comment by NewOldMax** [comment]
done
